### ISSUE TITLE
multiple tei:text elements

### ISSUE THREAD

**Issue by babslgam** [karl-kraus/legalkraus-archiv#1]
@csae8092 do you know, if this exists on purpose?
https://github.com/karl-kraus/legalkraus-archiv/blob/main/data/editions/D_000195-047-000.xml#L543-L547

**Comment by csae8092** [comment]
That's pretty sure a mistake

**Comment by babslgam** [comment]
> That's pretty sure a mistake

thanks, i updated my xslt. should we close this or is the data still being corrected?

**Comment by csae8092** [comment]
I'll try to fix the data
